### ISSUE TITLE
Current Password Field BG color

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/checkmate#1275]
While using dark theme, the "Current Password" field on the Password page has a white background on initial visit:

![image](https://github.com/user-attachments/assets/392512c4-8abb-42f0-834f-ea52929356cd)

Steps to reproduce:

1.  Go to `Monitor` page or any other top level page
2.  Expand the account menu item and navigate to "Password"

**Comment by saksham-malhotra-27** [comment]
Hey ! I can do this one if you say

**Comment by gorkem-bwl** [comment]
> Hey ! I can do this one if you say

Sure! Go ahead please. Make sure you deploy the app and send a screenshot showing it is fixed.

**Comment by saksham-malhotra-27** [comment]
Alright !

**Comment by saksham-malhotra-27** [comment]
Hi ,
I tried reproducing the issue with the "Current Password" field on the Password page when using the dark theme. However, when I visited the page, the background color appeared correct, matching the dark theme, rather than showing a white background as described.

Could you kindly confirm the following to help me understand the issue better?

1. Browser & Version: Could you let me know which browser and version you were using when you encountered the problem?
2. Steps to Reproduce: Did the issue occur immediately after visiting the page, or was there any delay in loading the theme?
3. Clearing Cache: Have you tried clearing the browser cache or testing in an incognito window to ensure the issue persists?

This will help me troubleshoot more effectively.

Additionally, I've noticed that if we use Google-suggested passwords or passwords saved in Google, we encounter the white background in the text field for a moment. I've attached two screenshots for reference:

1. My view, where the background appears correct:
![image](https://github.com/user-attachments/assets/30af5482-f3f5-4cbe-a869-e348cb2165ad)

2. White background issue, which occurs when using Google-suggested passwords:
![image](https://github.com/user-attachments/assets/92339345-8481-45dd-88f5-266770590efb)

If the bug is being reproduced in this way, please let me know, and I can investigate further.

Thank you for your help!

**Comment by saksham-malhotra-27** [comment]
If the issue is due to Google’s remembered passwords, it applies here as well, as shown in the screenshot:
![image](https://github.com/user-attachments/assets/2bcb3b19-9fc3-4c8e-8072-87678b220f2a)

This seems to be related to Chrome's autofill feature, which remembers certain fields like email or password. It’s possible that whenever these remembered fields are used, this problem arises.

This appears to be related to Chrome's autofill feature, which remembers fields like email or password. Could this behavior be linked to the issue, or can it be considered negligible since the white background doesn’t appear in other scenarios?

**Comment by saksham-malhotra-27** [comment]
Hey!
I did some research and came across a similar issue that others have faced. Here's an example I found:
[Elastic EUI Issue](https://github.com/elastic/eui/issues/2469)

I made a few modifications to the code, and it’s working now! 🎉
Check it out:
![image](https://github.com/user-attachments/assets/9661d466-fa34-457d-b282-ddffa5feb663)
![image](https://github.com/user-attachments/assets/daf634df-6ee9-4f63-a566-c635a50c52a8)
![image](https://github.com/user-attachments/assets/459cac2b-d2b0-4708-9e6d-e60659e33f04)
![image](https://github.com/user-attachments/assets/32af5f93-33c9-4a3d-8115-3725572283f0)

Let me know what you think!

**Comment by marcelluscaio** [comment]
Nice @saksham-malhotra-27 ! Did you open a PR for that?

**Comment by gorkem-bwl** [comment]
Looks great! It's an issue with most of the apps I saw and never thought it could be fixed. :)

**Comment by saksham-malhotra-27** [comment]
Hey! Just about to open a PR.
Let me know if everything looks good.

**Comment by saksham-malhotra-27** [comment]
Hey! It would be great if you could review my PR and share any suggestions for improvement.

**Comment by saksham-malhotra-27** [comment]
Hey @gorkem-bwl @marcelluscaio ! I submitted a PR related to this a couple of days ago. Could you please review it when you get a chance?
