### ISSUE TITLE
Issues when content area stretches below the sidebar

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/checkmate#1290]
When the content menu's height is more than the browser window, the sidebar doesn't stretch to the bottom. Under normal conditions (e.g check Settings) the sidebar stretches all the way to the bottom.

This is how it looks for Infra monitor (should be fixed):

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/5b39da28-4211-4c65-baa9-77cc65002699">

This is how it looks for Settings page (the right behaviour):

<img width="1378" alt="image" src="https://github.com/user-attachments/assets/1815e43b-7f5f-4a4f-9fe7-742bc056e5ba">

Also, the "MENU" category name overflows. The sidebar menu should be completely visible regarding the height of the contents area on the right, and MENU category shouldn't overflow.

**Comment by RishistavRay** [comment]
@gorkem-bwl Can you please assign me this task? I'd like to work on it. Thanks!

**Comment by RishistavRay** [comment]
I also found increasing the window size, pushes the profile icon and info outside of its container.
![image](https://github.com/user-attachments/assets/230852b6-65c6-43dc-959d-c6c38c47110a)

Additionally, the left collapsible menu does not have scroll functionality, which is necessary for adding additional items in the future.

**Comment by gorkem-bwl** [comment]
Go ahead @RishistavRay - please send as many videos/screenshots as possible with your PR as this is a tricky area :)

**Comment by ajhollid** [comment]
> I also found increasing the window size, pushes the profile icon and info outside of its container. ![image](https://private-user-images.githubusercontent.com/132870323/393562901-f5e4a4fc-28d9-40bb-a684-1c0b5b49fb01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MDkzNDUsIm5iZiI6MTczMzcwOTA0NSwicGF0aCI6Ii8xMzI4NzAzMjMvMzkzNTYyOTAxLWY1ZTRhNGZjLTI4ZDktNDBiYi1hNjg0LTFjMGI1YjQ5ZmIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwMTUwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDhhYTQwN2E4MjNlZDY2YTYxYTAxZGM4MDZkMGU3YjJjYTViMWIxMjI2MDZjZDhmN2YwYzNhYjg1OGJmYmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UqrE1OjapTsREgy1qHVeNck-ZtdENq06jzTG90I03-E)
> 
> Additionally, the left collapsible menu does not have scroll functionality, which is necessary for adding additional items in the future.

@RishistavRay I don't believe we want scrollability in the sidebar, it should be full window height at all times.  @gorkem-bwl can you confirm on this point?

**Comment by gorkem-bwl** [comment]
> @RishistavRay I don't believe we want scrollability in the sidebar, it should be full window height at all times. @gorkem-bwl can you confirm on this point?

I was assuming that we can have full height, but the menu is visible at all times. For example if the content area (on the right) have a 2-page length, and the user wants to scroll to the bottom, menu can still be visible. What do you think?

**Comment by RishistavRay** [comment]
@gorkem-bwl Yes you can have the menu height cover the entire height of the window (regardless of how long the content page is)

The scrollability @ajhollid is mentioning was my suggestion for the case where content area (on the right) is shorter than the minimum height of the left menu to display all items

![image](https://github.com/user-attachments/assets/a24a6039-3454-4abe-b330-464f65e3a379)

Here, half the menu is inaccessible due to lack of scrolling, but you can scroll the content area on the right.

**Comment by gorkem-bwl** [comment]
Right - got it now :) Your video is very clear and to the point. I think this is what we need to do. Such a small screen is usually for mobile devices and I don't think anyone would see such behaviour on a laptop/desktop. Hence, in case of a mobile device, can you also think of a hamburger menu, so that the content area is larger and we have more space for graphs?

**Comment by RishistavRay** [comment]
It's not a small screen issue. This issue is prevalent on a desktop screen with 110% zoom and above. This can also make it an accessibility issue for regular users and farsighted users.

Here you can see Docs and Changelog (items of the Other sub-menu) are inaccessible at 120% zoom
![image](https://github.com/user-attachments/assets/3a745b00-5317-4cb5-9f2a-239920a22714)

Lets recap:
1) I'm working on a PR that addresses the issues explained in the ticket's description
2) We can decide whether scrolling should or should not be included
3) I can certainly look into designing and implementing a hamburger-style menu for phone screens as part of a separate enhancement effort.

Let me know your thoughts :)
